# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eb85b1f11346761d5f09d658ce637b76e0f4fcc9c7867fcbba170289d231ef108c3bbe467b16fa017437f12d182ce9ffa284132b034cd2c6ddc2df676a3db49

test:
  secret_key_base: 187ee3df2378bbf43605e2ba9ac9dc3f8d64393bb056c3df6be68b0ab984031b70932cfeaf328fc5390fcd0309018e103e64be1848d7f26145911962d4af2b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
